<a href="https://colab.research.google.com/github/ThisIsFarhan/pytorch-codes/blob/main/01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

#Creation

In [4]:
a = torch.empty(2,3)

In [6]:
type(a)

torch.Tensor

In [7]:
z = torch.zeros(2,3)

In [8]:
z

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(2,3)

tensor([[0.6985, 0.6443, 0.4540],
        [0.6182, 0.9182, 0.8858]])

In [11]:
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [13]:
torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ]
)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

#Shapes

In [18]:
x = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ]
)

In [19]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)

tensor([[133487095135632,       140112464,       139709552],
        [              0,               0,       136986400]])

In [23]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

#Datatype

In [25]:
x.dtype

torch.int64

In [26]:
torch.tensor([
    [1,2,3]
],dtype=torch.float64)

tensor([[1., 2., 3.]], dtype=torch.float64)

In [29]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#Reduction Operations

In [32]:
x = torch.rand(2,2)
x

tensor([[0.6150, 0.4967],
        [0.4521, 0.0575]])

In [33]:
x+2

tensor([[2.6150, 2.4967],
        [2.4521, 2.0575]])

In [39]:
e = torch.randint(size=(2,3),low=0, high=10,dtype=torch.float32)
e

tensor([[9., 4., 4.],
        [5., 4., 0.]])

In [40]:
#Sum
torch.sum(e)

tensor(26.)

In [41]:
#Sum along column
torch.sum(e,dim=0)

tensor([14.,  8.,  4.])

In [42]:
#Sum along row
torch.sum(e,dim=1)

tensor([17.,  9.])

In [43]:
#Mean
torch.mean(e)

tensor(4.3333)

In [44]:
#Mean along column
torch.mean(e,dim=0)

tensor([7., 4., 2.])

In [45]:
#Mean along row
torch.mean(e,dim=1)

tensor([5.6667, 3.0000])

In [46]:
#Max
torch.max(e)

tensor(9.)

In [47]:
#Max along column
torch.max(e,dim=0)

torch.return_types.max(
values=tensor([9., 4., 4.]),
indices=tensor([0, 0, 0]))

In [48]:
#Max along row
torch.max(e,dim=1)

torch.return_types.max(
values=tensor([9., 5.]),
indices=tensor([0, 0]))

In [50]:
torch.std(e,dim=1)

tensor([2.8868, 2.6458])

In [51]:
torch.std(e,dim=0)

tensor([2.8284, 0.0000, 2.8284])

#Matrix Multiplication

In [56]:
a = torch.randint(size=(2,3),low=0,high=10)
b = torch.randint(size=(3,2),low=0,high=10)

In [57]:
print(a)
print(b)

tensor([[9, 6, 9],
        [1, 9, 2]])
tensor([[1, 2],
        [9, 7],
        [2, 9]])


In [58]:
torch.matmul(a,b)

tensor([[ 81, 141],
        [ 86,  83]])

In [59]:
torch.transpose(a,0,1)

tensor([[9, 1],
        [6, 9],
        [9, 2]])

In [64]:
sq = torch.randint(size=(2,2),low=0,high=10,dtype=torch.float64)
sq

tensor([[8., 2.],
        [6., 1.]], dtype=torch.float64)

In [65]:
torch.det(sq)

tensor(-4., dtype=torch.float64)

In [66]:
torch.inverse(sq)

tensor([[-0.2500,  0.5000],
        [ 1.5000, -2.0000]], dtype=torch.float64)

#Functions

In [82]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float64)
k

tensor([[6., 5., 6.],
        [3., 6., 0.]], dtype=torch.float64)

In [83]:
torch.log(k)

tensor([[1.7918, 1.6094, 1.7918],
        [1.0986, 1.7918,   -inf]], dtype=torch.float64)

In [84]:
torch.exp(k)

tensor([[403.4288, 148.4132, 403.4288],
        [ 20.0855, 403.4288,   1.0000]], dtype=torch.float64)

In [85]:
torch.sqrt(k)

tensor([[2.4495, 2.2361, 2.4495],
        [1.7321, 2.4495, 0.0000]], dtype=torch.float64)

In [86]:
torch.sigmoid(k) #sigmoid(x) = 1 / (1 + exp(-x))

tensor([[0.9975, 0.9933, 0.9975],
        [0.9526, 0.9975, 0.5000]], dtype=torch.float64)

In [94]:
softmax_column = torch.softmax(k,dim=0)
print(softmax_column)
torch.sum(softmax_column,dim=0)

tensor([[0.9526, 0.2689, 0.9975],
        [0.0474, 0.7311, 0.0025]], dtype=torch.float64)


tensor([1.0000, 1.0000, 1.0000], dtype=torch.float64)

In [95]:
softmax_row = torch.softmax(k,dim=1)
print(softmax_row)
torch.sum(softmax_row,dim=1)

tensor([[0.4223, 0.1554, 0.4223],
        [0.0473, 0.9503, 0.0024]], dtype=torch.float64)


tensor([1.0000, 1.0000], dtype=torch.float64)

#Reshaping Tensors

In [96]:
a = torch.ones(4,4)

In [97]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
a.reshape(2,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [100]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [105]:
b = torch.rand(2,3,4)
b

tensor([[[0.3055, 0.4874, 0.2647, 0.3518],
         [0.8371, 0.9271, 0.6741, 0.1249],
         [0.3156, 0.8468, 0.3651, 0.0916]],

        [[0.6161, 0.0561, 0.4970, 0.4385],
         [0.5048, 0.3810, 0.4269, 0.1977],
         [0.1699, 0.6641, 0.9510, 0.1006]]])

In [111]:
res = b.permute(2,1,0)

In [113]:
res

tensor([[[0.3055, 0.6161],
         [0.8371, 0.5048],
         [0.3156, 0.1699]],

        [[0.4874, 0.0561],
         [0.9271, 0.3810],
         [0.8468, 0.6641]],

        [[0.2647, 0.4970],
         [0.6741, 0.4269],
         [0.3651, 0.9510]],

        [[0.3518, 0.4385],
         [0.1249, 0.1977],
         [0.0916, 0.1006]]])

In [114]:
res.shape

torch.Size([4, 3, 2])

In [121]:
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [127]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])