<a href="https://colab.research.google.com/github/ThisIsFarhan/pytorch-codes/blob/main/03_TrainingPipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
encoder = LabelEncoder()
encoder.fit(df["species"])
df["encoded_species"] = encoder.transform(df["species"])

In [5]:
df

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     encoded_species  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
..               ...  
145                2  
146                2  
147                2  
148                2  
149                2  

[150 rows x 6 columns]

In [6]:
df["species"].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [7]:
df["encoded_species"].value_counts()

encoded_species
0    50
1    50
2    50
Name: count, dtype: int64

In [8]:
df = df[df["encoded_species"] != 2]

In [9]:
df["encoded_species"].value_counts()

encoded_species
0    50
1    50
Name: count, dtype: int64

In [10]:
df.drop(columns=["species"],inplace=True)

<ipython-input-10-d2d58303af85>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["species"],inplace=True)


In [11]:
df

sepal_length  sepal_width  petal_length  petal_width  encoded_species
0            5.1          3.5           1.4          0.2                0
1            4.9          3.0           1.4          0.2                0
2            4.7          3.2           1.3          0.2                0
3            4.6          3.1           1.5          0.2                0
4            5.0          3.6           1.4          0.2                0
..           ...          ...           ...          ...              ...
95           5.7          3.0           4.2          1.2                1
96           5.7          2.9           4.2          1.3                1
97           6.2          2.9           4.3          1.3                1
98           5.1          2.5           3.0          1.1                1
99           5.7          2.8           4.1          1.3                1

[100 rows x 5 columns]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, :-1], df.iloc[:, -1], test_size=0.2)

In [13]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
X_train

array([[-1.16779009,  0.24513248, -1.08076399, -1.03397891],
       [-0.86347997,  0.01167298, -0.94330593, -1.20997532],
       [-1.01563503, -0.22178653, -1.01203496, -1.20997532],
       [ 1.11453582, -0.45524603,  0.9811069 ,  0.9019816 ],
       [-1.01563503, -0.22178653, -1.01203496, -0.8579825 ],
       [ 1.87531113,  0.01167298,  1.25602302,  1.25397442],
       [-0.71132491,  0.94551098, -0.8745769 , -0.32999327],
       [-0.10270467,  0.71205148, -0.94330593, -0.68198609],
       [-0.71132491,  0.71205148, -0.94330593, -1.03397891],
       [-0.10270467, -0.22178653,  1.11856496,  1.25397442],
       [-0.55916985,  1.41242998, -0.94330593, -0.68198609],
       [ 0.35376052,  1.64588948, -0.80584787, -0.8579825 ],
       [-0.25485973,  1.41242998, -0.94330593, -1.03397891],
       [-0.71132491,  0.94551098, -1.08076399, -0.8579825 ],
       [ 1.11453582, -2.08946253,  1.11856496,  1.25397442],
       [ 2.02746619, -0.68870553,  1.32475205,  1.07797801],
       [ 0.50591558,  2.

In [15]:
y_train

2     0
34    0
12    0
97    1
45    0
     ..
58    1
93    1
6     0
69    1
36    0
Name: encoded_species, Length: 80, dtype: int64

In [16]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train.to_numpy())
y_test_tensor = torch.from_numpy(y_test.to_numpy())

In [17]:
X_train_tensor.shape

torch.Size([80, 4])

In [18]:
y_train_tensor.shape

torch.Size([80])

In [19]:
X_train_tensor.shape

torch.Size([80, 4])

In [20]:
class MyNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64, requires_grad=True)

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

In [21]:
learning_rate = 0.1
epochs = 100

model = MyNN(X_train_tensor)
for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)
  loss = model.loss_function(y_pred, y_train_tensor)
  loss.backward()
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.938548659834725
Epoch: 2, Loss: 0.9178726115727639
Epoch: 3, Loss: 0.8988341615518414
Epoch: 4, Loss: 0.8813521073614868
Epoch: 5, Loss: 0.8653408060968671
Epoch: 6, Loss: 0.8507116874577914
Epoch: 7, Loss: 0.8373746918147452
Epoch: 8, Loss: 0.825239595359438
Epoch: 9, Loss: 0.8142171942050634
Epoch: 10, Loss: 0.8042203290836065
Epoch: 11, Loss: 0.7951647414657574
Epoch: 12, Loss: 0.7869697600352459
Epoch: 13, Loss: 0.7795588231888977
Epoch: 14, Loss: 0.772859848470589
Epoch: 15, Loss: 0.7668054635789943
Epoch: 16, Loss: 0.7613331159155783
Epoch: 17, Loss: 0.7563850787313668
Epoch: 18, Loss: 0.7519083720002174
Epoch: 19, Loss: 0.7478546154195468
Epoch: 20, Loss: 0.7441798296386247
Epoch: 21, Loss: 0.7408442001418751
Epoch: 22, Loss: 0.737811816343455
Epoch: 23, Loss: 0.7350503965199752
Epoch: 24, Loss: 0.7325310073269518
Epoch: 25, Loss: 0.7302277848865745
Epoch: 26, Loss: 0.7281176628472779
Epoch: 27, Loss: 0.7261801114246066
Epoch: 28, Loss: 0.7243968902458005
Epoch

In [22]:
model.weights

tensor([[ 0.0604],
        [ 0.1049],
        [ 0.1854],
        [-0.1707]], dtype=torch.float64, requires_grad=True)

In [23]:
model.bias

tensor([0.0009], dtype=torch.float64, requires_grad=True)

In [34]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  #print(y_pred)
  y_pred = (y_pred > 0.5).float()
  #print(y_pred)
  accuracy = (y_pred == y_test_tensor).float().mean()
  #print(accuracy)
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5
