<a href="https://colab.research.google.com/github/ThisIsFarhan/pytorch-codes/blob/main/04_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__() #calling the constructor of the super class with the constructor of child class
    self.linear = nn.Linear(num_features, 1) #(input, output)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features) #z = wx + b
    out = self.sigmoid(out) #sig(z)

    return out


features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)


tensor([[0.4938],
        [0.4845],
        [0.5457],
        [0.5212],
        [0.5482],
        [0.4579],
        [0.5741],
        [0.4803],
        [0.5242],
        [0.4883]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear.weight

Parameter containing:
tensor([[ 0.3112, -0.1609,  0.2010, -0.3994, -0.1510]], requires_grad=True)

In [7]:
model.linear.bias

Parameter containing:
tensor([0.0608], requires_grad=True)

In [8]:
!pip install torchinfo

In [10]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [16]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__() #calling the constructor of the super class with the constructor of child class
    self.linear1 = nn.Linear(num_features, 3) #(input, output)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out


features = torch.rand(10,5)
model = Model(features.shape[1])
print(model(features))
print(summary(model,input_size=(10,5)))
print(f"Layer 1 weights: {model.linear1.weight}")
print(f"Layer 2 weights: {model.linear2.weight}")
print(f"Layer 1 bias: {model.linear1.bias}")
print(f"Layer 2 bias: {model.linear2.bias}")

tensor([[0.5807],
        [0.5900],
        [0.5807],
        [0.5807],
        [0.5807],
        [0.5807],
        [0.5807],
        [0.5807],
        [0.5807],
        [0.5813]], grad_fn=<SigmoidBackward0>)
Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
Layer 1 weights: Parameter containing:
tensor([[ 0.1641,  0.0075, -0.1695, -0.4057, -0.2363],
        [-0.3619, -0.3272, -0.3936,  0.0839, -0.1613],
 

In [19]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__() #calling the constructor of the super class with the constructor of child class
    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )


  def forward(self, features):
    out = self.network(features)
    return out


features = torch.rand(10,5)
model = Model(features.shape[1])
print(model(features))
print(summary(model,input_size=(10,5)))

tensor([[0.3282],
        [0.3563],
        [0.3585],
        [0.3606],
        [0.3684],
        [0.3293],
        [0.3658],
        [0.3434],
        [0.3364],
        [0.3724]], grad_fn=<SigmoidBackward0>)
Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
